//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPU_Catalog3.LangResource {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPU_Catalog3.LangResource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cores.
        /// </summary>
        public static string cores {
            get {
                return ResourceManager.GetString("cores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        public static string detailedInformationLabel {
            get {
                return ResourceManager.GetString("detailedInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bits depth:.
        /// </summary>
        public static string detBitdepthLabel {
            get {
                return ResourceManager.GetString("detBitdepthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string detDescriptionLabel {
            get {
                return ResourceManager.GetString("detDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Frequency:.
        /// </summary>
        public static string detFrequencyLabel {
            get {
                return ResourceManager.GetString("detFrequencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GHz.
        /// </summary>
        public static string detGHZLabel {
            get {
                return ResourceManager.GetString("detGHZLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        public static string detInformationLabel {
            get {
                return ResourceManager.GetString("detInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manufacturer:.
        /// </summary>
        public static string detManufacturerLabel {
            get {
                return ResourceManager.GetString("detManufacturerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Model:.
        /// </summary>
        public static string detModelLabel {
            get {
                return ResourceManager.GetString("detModelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of cores:.
        /// </summary>
        public static string detNumcoresLabel {
            get {
                return ResourceManager.GetString("detNumcoresLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter bits depth.
        /// </summary>
        public static string entryBitsdepth {
            get {
                return ResourceManager.GetString("entryBitsdepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter frequency.
        /// </summary>
        public static string entryFrequency {
            get {
                return ResourceManager.GetString("entryFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter latitude.
        /// </summary>
        public static string entryLatitude {
            get {
                return ResourceManager.GetString("entryLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter longitude.
        /// </summary>
        public static string entryLongitude {
            get {
                return ResourceManager.GetString("entryLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter manufacturer.
        /// </summary>
        public static string entryManufacturer {
            get {
                return ResourceManager.GetString("entryManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter model.
        /// </summary>
        public static string entryModel {
            get {
                return ResourceManager.GetString("entryModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter number of cores.
        /// </summary>
        public static string entryNumcores {
            get {
                return ResourceManager.GetString("entryNumcores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter video url.
        /// </summary>
        public static string entryvideoUrl {
            get {
                return ResourceManager.GetString("entryvideoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Font:.
        /// </summary>
        public static string fontLabel {
            get {
                return ResourceManager.GetString("fontLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interface:.
        /// </summary>
        public static string interfaceLabelT {
            get {
                return ResourceManager.GetString("interfaceLabelT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language:.
        /// </summary>
        public static string languageLabelT {
            get {
                return ResourceManager.GetString("languageLabelT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string loginButtonT {
            get {
                return ResourceManager.GetString("loginButtonT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string loginEntryPH {
            get {
                return ResourceManager.GetString("loginEntryPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string passEntryPH {
            get {
                return ResourceManager.GetString("passEntryPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registry.
        /// </summary>
        public static string regLabelT {
            get {
                return ResourceManager.GetString("regLabelT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string settingsLabelT {
            get {
                return ResourceManager.GetString("settingsLabelT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme:.
        /// </summary>
        public static string themeLabelT {
            get {
                return ResourceManager.GetString("themeLabelT", resourceCulture);
            }
        }
    }
}
