# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CPU_Catalog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'FirebaseUI/Storage'
  pod 'Kingfisher', '~> 6.1'
  # Pods for CPU_Catalog

  target 'CPU_CatalogTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'CPU_CatalogUITests' do
    # Pods for testing
  end

end
